import "@/app/globals.css";
import ThemeToggle from "@/components/ThemeToggle";

export const metadata = {
  title: "Fungi | Personal Portfolio Template",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet" />
        <link rel="icon" href="../images/developer/favicon.ico" sizes="any" />
      </head>
      <body className="dark:bg-dark" id="__next">
        <div className="fixed top-1/2 -right-[10px] -translate-y-1/2 transition-all duration-500 hover:right-0 z-[99999]">
          <ThemeToggle 
            lightBg={'bg-main-light'}
            lightText={'text-main-light'}
            darkBgDark={'dark:bg-main-dark'} 
            darkTextDark={'dark:text-main-dark'}
            darkBgLight={'dark:bg-main-light'}
            darkTextLight={'dark:text-main-light'}
            darkBg={'bg-main-dark'}
            darkText={'text-main-dark'}
          />
        </div>
        {children}
      </body>
    </html>
  );
}
